<!DOCTYPE owo-ui [
        <!ELEMENT owo-ui (components|templates)*>
        <!ATTLIST owo-ui
                xmlns:xsi CDATA #REQUIRED
                xsi:noNamespaceSchemaLocation CDATA #REQUIRED>
        <!ELEMENT components (flow-layout)*>
        <!ELEMENT flow-layout (children|sizing|vertical-alignment|horizontal-alignment|gap|positioning|surface)*>
        <!ATTLIST flow-layout
                direction CDATA #REQUIRED>
        <!ELEMENT children (label|scroll|template|flow-layout|button)*>
        <!ELEMENT label (positioning|text)*>
        <!ATTLIST label
                id CDATA #REQUIRED>
        <!ELEMENT positioning (#PCDATA)>
        <!ATTLIST positioning
                type CDATA #REQUIRED>
        <!ELEMENT text (#PCDATA)>
        <!ATTLIST text
                translate CDATA #REQUIRED>
        <!ELEMENT scroll (flow-layout|scrollbar|sizing)*>
        <!ATTLIST scroll
                direction CDATA #REQUIRED>
        <!ELEMENT template (name)*>
        <!ATTLIST template
                name CDATA #REQUIRED>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT sizing (horizontal|vertical)*>
        <!ELEMENT horizontal (#PCDATA)>
        <!ATTLIST horizontal
                method CDATA #REQUIRED>
        <!ELEMENT vertical-alignment (#PCDATA)>
        <!ELEMENT horizontal-alignment (#PCDATA)>
        <!ELEMENT gap (#PCDATA)>
        <!ELEMENT scrollbar (flat)*>
        <!ELEMENT flat (#PCDATA)>
        <!ELEMENT vertical (#PCDATA)>
        <!ATTLIST vertical
                method CDATA #REQUIRED>
        <!ELEMENT button (text|margins)*>
        <!ATTLIST button
                id CDATA #REQUIRED>
        <!ELEMENT margins (right|top|bottom)*>
        <!ELEMENT right (#PCDATA)>
        <!ELEMENT top (#PCDATA)>
        <!ELEMENT bottom (#PCDATA)>
        <!ELEMENT surface (vanilla-translucent)*>
        <!ELEMENT vanilla-translucent (#PCDATA)>
        <!ELEMENT templates (main-button-layout)*>
        <!ELEMENT main-button-layout (main-button)*>
        <!ELEMENT main-button (text|sizing|margins)*>
        <!ATTLIST main-button
                id CDATA #REQUIRED>
        ]>
<owo-ui xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/wisp-forest/owo-lib/1.20.2/owo-ui.xsd">
    <components>
        <flow-layout direction="vertical">
            <children>
                <label id="title">
                    <positioning type="absolute">20,20</positioning>
                    <text translate="true">fzmm.gui.title.main</text>
                </label>

                <scroll direction="vertical">
                    <flow-layout direction="ltr-text-flow">
                        <children>
                            <template name="main-button-layout">
                                <name>imagetext</name>
                            </template>
                            <template name="main-button-layout">
                                <name>textFormat</name>
                            </template>
                            <template name="main-button-layout">
                                <name>playerStatue</name>
                            </template>
                            <template name="main-button-layout">
                                <name>encryptbook</name>
                            </template>
                            <template name="main-button-layout">
                                <name>headGenerator</name>
                            </template>
                            <template name="main-button-layout">
                                <name>converters</name>
                            </template>
                            <template name="main-button-layout">
                                <name>history</name>
                            </template>
                            <template name="main-button-layout">
                                <name>headGallery</name>
                            </template>
                            <template name="main-button-layout">
                                <name>bannerEditor</name>
                            </template>
                        </children>

                        <sizing>
                            <horizontal method="fill">100</horizontal>
                        </sizing>

                        <vertical-alignment>top</vertical-alignment>
                        <horizontal-alignment>center</horizontal-alignment>

                        <gap>5</gap>

                    </flow-layout>

                    <scrollbar>
                        <flat>#FFFFFF</flat>
                    </scrollbar>

                    <sizing>
                        <vertical method="fill">70</vertical>
                        <horizontal method="fill">80</horizontal>
                    </sizing>
                </scroll>

                <flow-layout direction="vertical">
                    <children>

                        <button id="config-button">
                            <text translate="true">fzmm.gui.title.configs</text>

                            <margins>
                                <right>20</right>
                                <top>20</top>
                            </margins>
                        </button>

                    </children>

                    <positioning type="relative">100,0</positioning>

                    <vertical-alignment>bottom</vertical-alignment>
                    <horizontal-alignment>right</horizontal-alignment>
                </flow-layout>

                <flow-layout direction="vertical">
                    <children>

                        <button id="back-button">
                            <text translate="true">fzmm.gui.button.back</text>

                            <margins>
                                <right>20</right>
                                <bottom>20</bottom>
                            </margins>
                        </button>

                    </children>

                    <positioning type="relative">100,100</positioning>

                    <vertical-alignment>bottom</vertical-alignment>
                    <horizontal-alignment>right</horizontal-alignment>
                </flow-layout>

            </children>

            <vertical-alignment>center</vertical-alignment>
            <horizontal-alignment>center</horizontal-alignment>

            <surface>
                <vanilla-translucent/>
            </surface>
        </flow-layout>
    </components>

    <templates>
        <main-button-layout>
            <fzmm.main-button id="{{name}}-button">
                <text translate="true">fzmm.gui.title.{{name}}</text>
                <sizing>
                    <horizontal method="fixed">150</horizontal>
                    <vertical method="fixed">60</vertical>
                </sizing>

                <margins>
                    <bottom>5</bottom>
                </margins>
            </fzmm.main-button>
        </main-button-layout>
    </templates>
</owo-ui>